apiVersion: security-profiles-operator.x-k8s.io/v1alpha1
kind: SeccompProfile
metadata:
  name: complainer
  namespace: seccomp-test
  annotations:
    description: >-
      Seccomp profile to set complain mode (log all syscalls)
spec:
  defaultAction: SCMP_ACT_LOG
